(function(){
  const style=document.createElement('link');style.rel='stylesheet';style.href='/app-preview/treatment-tray.css';document.head.append(style);
  const list=document.getElementById('storyList'),trigger=document.getElementById('storyTrigger'),logo=document.getElementById('logo'),card=document.getElementById('pinCard'),preview=card.querySelector('.pin-preview'),photo=preview.querySelector('.photo');
  trigger.onclick=()=>{list.hidden=!list.hidden};list.querySelectorAll('button').forEach(button=>button.onclick=()=>{document.getElementById('selectedTitle').textContent=button.dataset.title;document.getElementById('selectedMeta').textContent=button.dataset.meta;list.hidden=true});
  const tray=document.createElement('div');tray.className='treatment-section';tray.innerHTML='<label>CHOOSE A LOOK</label><div class="treatment-tray"></div>';preview.after(tray);const row=tray.querySelector('.treatment-tray'),adjustments=document.createElement('div');adjustments.className='pin-adjustments';
  [...card.querySelectorAll(':scope>label,:scope>.choices')].forEach(node=>adjustments.append(node));tray.after(adjustments);
  const options=[['original','Original'],['bark','Bark'],['sage','Sage'],['sand','Sand'],['terracotta','Terracotta']];options.forEach(([value,label],index)=>{const button=document.createElement('button');button.className='treatment-option'+(index===0?' selected':'');button.dataset.value=value;button.innerHTML='<span><img class="mini-photo" src="'+photo.src+'" alt=""><img class="mini-logo" '+(value==='original'?'hidden':'src="/images/pinterest-logos/logo-'+value+'.png"')+' alt=""></span><b>'+label+'</b><i>✓</i>';button.onclick=()=>{row.querySelectorAll('button').forEach(item=>item.classList.toggle('selected',item===button));const original=value==='original';logo.hidden=original;adjustments.hidden=original;if(!original){logo.src=`/images/pinterest-logos/logo-${value}.png`;const colorButton=adjustments.querySelector(`[data-control="color"] [data-value="${value}"]`);colorButton?.click()}};row.append(button)});logo.hidden=true;adjustments.hidden=true;
  document.querySelectorAll('.choices').forEach(group=>group.querySelectorAll('button').forEach(button=>button.onclick=()=>{group.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');const type=group.dataset.control,value=button.dataset.value;if(type==='color')logo.src=`/images/pinterest-logos/logo-${value}.png`;else{logo.classList.remove(type==='size'?'small':'left',type==='size'?'medium':'right');logo.classList.add(value)}}));list.hidden=true;
})();
