(function(){
  const style=document.createElement('link');style.rel='stylesheet';style.href='/app-preview/treatment-tray.css';document.head.append(style);
  const list=document.getElementById('storyList'),trigger=document.getElementById('storyTrigger'),card=document.getElementById('pinCard'),preview=card.querySelector('.pin-preview'),source=preview.querySelector('.photo').src,looks=['original','bark','sage','sand','terracotta'];
  trigger.onclick=()=>{list.hidden=!list.hidden};list.querySelectorAll('button').forEach(button=>button.onclick=()=>{document.getElementById('selectedTitle').textContent=button.dataset.title;document.getElementById('selectedMeta').textContent=button.dataset.meta;list.hidden=true});list.hidden=true;
  preview.innerHTML='';preview.classList.add('pin-filter-carousel');looks.forEach((look,index)=>{const slide=document.createElement('div');slide.className='pin-filter-slide';slide.innerHTML='<img class="photo" src="'+source+'" alt="'+(look==='original'?'Original photo':look+' logo treatment')+'">'+(look==='original'?'':'<img class="logo small left" src="/images/pinterest-logos/logo-'+look+'.png" alt="">');preview.append(slide)});
  const caption=document.createElement('div');caption.className='pin-filter-caption';caption.innerHTML='<b>Original</b><span>'+looks.map((_,i)=>'<i'+(i===0?' class="active"':'')+'></i>').join('')+'</span><small>Swipe the photo to compare looks</small>';preview.after(caption);
  const adjustments=document.createElement('div');adjustments.className='pin-adjustments';[...card.querySelectorAll(':scope>label,:scope>.choices')].forEach(node=>adjustments.append(node));caption.after(adjustments);adjustments.hidden=true;
  let current=0,settle;function show(index){current=Math.max(0,Math.min(looks.length-1,index));caption.querySelector('b').textContent=looks[current][0].toUpperCase()+looks[current].slice(1);caption.querySelectorAll('i').forEach((dot,i)=>dot.classList.toggle('active',i===current));adjustments.hidden=current===0}
  preview.addEventListener('scroll',()=>{clearTimeout(settle);settle=setTimeout(()=>show(Math.round(preview.scrollLeft/preview.clientWidth)),80)});
  document.querySelectorAll('.choices').forEach(group=>group.querySelectorAll('button').forEach(button=>button.onclick=()=>{group.querySelectorAll('button').forEach(item=>item.classList.remove('active'));button.classList.add('active');const type=group.dataset.control,value=button.dataset.value;if(type==='color'){const index=looks.indexOf(value);preview.scrollTo({left:index*preview.clientWidth,behavior:'smooth'})}else preview.querySelectorAll('.logo').forEach(logo=>{logo.classList.remove(type==='size'?'small':'left',type==='size'?'medium':'right');logo.classList.add(value)})}));
})();
