const tabs=[...document.querySelectorAll('[data-tab]')],panels=[...document.querySelectorAll('.panel')],state=document.querySelector('#saveState');tabs.forEach(button=>button.addEventListener('click',()=>{tabs.forEach(x=>x.classList.toggle('active',x===button));panels.forEach(x=>x.classList.toggle('active',x.id===button.dataset.tab))}));let timer;document.querySelectorAll('textarea,[contenteditable]').forEach(field=>field.addEventListener('input',()=>{state.textContent='Saved on this device';clearTimeout(timer);timer=setTimeout(()=>{state.textContent='Synchronizing…';setTimeout(()=>state.textContent='Synchronized',650)},700)}));document.querySelectorAll('textarea').forEach(area=>{const fit=()=>{area.style.height='auto';area.style.height=area.scrollHeight+'px'};area.addEventListener('input',fit);fit()});
const library=document.createElement('div');library.className='template-library';library.innerHTML='<div class="template-heading"><div><b>Trail Journal templates</b><small>8 transparent PNGs · separate from Pins</small></div><span>Imported</span></div><div class="template-groups"><section><h2>Landscape · 1600 × 900</h2><div class="template-grid" data-orientation="landscape"></div></section><section><h2>Portrait · 1200 × 1500</h2><div class="template-grid" data-orientation="portrait"></div></section></div>';document.querySelector('#photos article').after(library);['landscape','portrait'].forEach(orientation=>{const grid=library.querySelector(`[data-orientation="${orientation}"]`);['bark','sand','sage','terracotta'].forEach(color=>{const button=document.createElement('button');button.className=`template-card ${color}`;button.innerHTML=`<span><img src="/images/templates/trail-journal/${orientation}-${color}.png" alt="${orientation} ${color} Trail Journal logo template"></span><b>${color[0].toUpperCase()+color.slice(1)}</b>`;button.onclick=()=>{library.querySelectorAll('.template-card').forEach(item=>item.classList.toggle('selected',item===button))};grid.append(button)})});

const storyBody=document.querySelector('.paper');
const writingTools=document.createElement('div');writingTools.className='writing-tools';writingTools.setAttribute('aria-label','Story formatting');writingTools.innerHTML='<label class="format-picker"><span>Text style</span><select aria-label="Text style"><option value="p">Paragraph</option><option value="h2">Section heading</option><option value="h3">Small heading</option></select></label><button type="button" class="link-tool" aria-expanded="false"><span aria-hidden="true">↗</span> Insert link</button><div class="link-panel" hidden><label><span>Link address</span><input type="url" inputmode="url" placeholder="https://example.com"></label><div><button type="button" class="cancel-link">Cancel</button><button type="button" class="apply-link">Add link</button></div><small>Select the words you want linked before opening this.</small></div>';storyBody.before(writingTools);
const formatPicker=writingTools.querySelector('select'),linkTool=writingTools.querySelector('.link-tool'),linkPanel=writingTools.querySelector('.link-panel'),linkInput=writingTools.querySelector('input');let savedStoryRange=null;
const rememberStorySelection=()=>{const selection=window.getSelection();if(!selection.rangeCount)return;const range=selection.getRangeAt(0);if(storyBody.contains(range.commonAncestorContainer))savedStoryRange=range.cloneRange()};
const restoreStorySelection=()=>{if(!savedStoryRange)return false;const selection=window.getSelection();selection.removeAllRanges();selection.addRange(savedStoryRange);return true};document.addEventListener('selectionchange',rememberStorySelection);
formatPicker.addEventListener('change',()=>{storyBody.focus();restoreStorySelection();document.execCommand('formatBlock',false,formatPicker.value);rememberStorySelection();storyBody.dispatchEvent(new Event('input',{bubbles:true}))});
linkTool.addEventListener('pointerdown',rememberStorySelection);linkTool.addEventListener('click',()=>{const opening=linkPanel.hidden;linkPanel.hidden=!opening;linkTool.setAttribute('aria-expanded',String(opening));if(opening)setTimeout(()=>linkInput.focus(),0)});
writingTools.querySelector('.cancel-link').addEventListener('click',()=>{linkPanel.hidden=true;linkTool.setAttribute('aria-expanded','false');linkInput.value=''});
writingTools.querySelector('.apply-link').addEventListener('click',()=>{let url=linkInput.value.trim();if(!url)return linkInput.focus();if(!/^(https?:|mailto:|tel:)/i.test(url))url='https://'+url;storyBody.focus();if(!restoreStorySelection()||savedStoryRange.collapsed){linkPanel.querySelector('small').textContent='Highlight the words in your story first, then choose Insert link.';return}document.execCommand('createLink',false,url);storyBody.querySelectorAll('a').forEach(link=>{link.target='_blank';link.rel='noopener noreferrer'});storyBody.dispatchEvent(new Event('input',{bubbles:true}));linkPanel.hidden=true;linkTool.setAttribute('aria-expanded','false');linkInput.value=''});
