backend:
  name: git-gateway
  branch: main

media_folder: images

collections:
  - name: blog
    label: Blog Posts
    folder: _posts
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Category, name: category, widget: select, options: [Trail Reports, Cheeto Diaries, Gear, Tips] }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
