ALTER TABLE instagram_post_drafts
  ADD COLUMN IF NOT EXISTS alt_text TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pinterest_reusable BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ;

